# Generated by Django 4.1.4 on 2022-12-18 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='logo_image',
            field=models.ImageField(blank=True, upload_to='mall/images/'),
        ),
    ]
