# Generated by Django 3.2 on 2022-12-19 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0004_cart_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='card_id',
            new_name='cart_id',
        ),
    ]
